package com.farmacia.igu;
import javax.swing.JOptionPane;
public class Pedidos extends javax.swing.JFrame {

    /**
     * Creates new form Pedidos
     */
    public Pedidos() {
        initComponents();
    }
    private boolean isAlphaNumeric(String word) {
        return word != null && word.matches("^[a-zA-Z0-9]*$");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nombreMedica = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tipoMedic = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cantidadMedic = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cofarmaRadioButton = new javax.swing.JRadioButton();
        empsephatRadioButton = new javax.swing.JRadioButton();
        cemefarRadioButton = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        farmPrincipal = new javax.swing.JCheckBox();
        farmSecundaria = new javax.swing.JCheckBox();
        confirmaBoton = new javax.swing.JButton();
        borrarBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre del Medicamento: ");

        nombreMedica.setText("jTextField1");
        nombreMedica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreMedicaActionPerformed(evt);
            }
        });

        jLabel2.setText("Tipo del Medicamento:");

        tipoMedic.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Analgésico", "Analéptico", "Anestésico", "Antiácido", "Antidepresivo", "Antibióticos" }));
        tipoMedic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoMedicActionPerformed(evt);
            }
        });

        jLabel3.setText("Cantidad de producto requerida:");

        cantidadMedic.setText("jTextField2");

        jLabel4.setText("Distribuidor:");

        cofarmaRadioButton.setText("Cofarma");
        cofarmaRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cofarmaRadioButtonActionPerformed(evt);
            }
        });

        empsephatRadioButton.setText("Empsephar");

        cemefarRadioButton.setText("Cemefar");

        jLabel5.setText("Sucursal:");

        farmPrincipal.setText("Farmacia Principal");
        farmPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                farmPrincipalActionPerformed(evt);
            }
        });

        farmSecundaria.setText("Farmacia Secundaria");
        farmSecundaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                farmSecundariaActionPerformed(evt);
            }
        });

        confirmaBoton.setText("Confirmar");
        confirmaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmaBotonActionPerformed(evt);
            }
        });

        borrarBoton.setText("Borrar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cantidadMedic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreMedica, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipoMedic, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(farmPrincipal)
                                .addGap(18, 18, 18)
                                .addComponent(farmSecundaria))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cofarmaRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(empsephatRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cemefarRadioButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(borrarBoton)
                                .addGap(28, 28, 28)
                                .addComponent(confirmaBoton)))))
                .addContainerGap(292, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreMedica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tipoMedic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cantidadMedic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cofarmaRadioButton)
                    .addComponent(empsephatRadioButton)
                    .addComponent(cemefarRadioButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(farmPrincipal)
                    .addComponent(farmSecundaria))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmaBoton)
                    .addComponent(borrarBoton))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cofarmaRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cofarmaRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cofarmaRadioButtonActionPerformed

    private void farmPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_farmPrincipalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_farmPrincipalActionPerformed

    private void farmSecundariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_farmSecundariaActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_farmSecundariaActionPerformed

    private void confirmaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmaBotonActionPerformed
        String nombreMedicamento = nombreMedica.getText();
        
        // Validar si es alfanumérico
        if (!isAlphaNumeric(nombreMedicamento)) {
            // Mostrar un mensaje de error o tomar alguna acción
            JOptionPane.showMessageDialog(this, "El nombre del medicamento no debe contener carateres alfanumérico.", "Error", JOptionPane.ERROR_MESSAGE);

            // Limpiar el campo o realizar alguna otra acción, según sea necesario
            nombreMedica.setText("");
            return;
    }  // TODO add your handling code here:
    }//GEN-LAST:event_confirmaBotonActionPerformed

    private void tipoMedicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoMedicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoMedicActionPerformed

    private void nombreMedicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreMedicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreMedicaActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrarBoton;
    private javax.swing.JTextField cantidadMedic;
    private javax.swing.JRadioButton cemefarRadioButton;
    private javax.swing.JRadioButton cofarmaRadioButton;
    private javax.swing.JButton confirmaBoton;
    private javax.swing.JRadioButton empsephatRadioButton;
    private javax.swing.JCheckBox farmPrincipal;
    private javax.swing.JCheckBox farmSecundaria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombreMedica;
    private javax.swing.JComboBox<String> tipoMedic;
    // End of variables declaration//GEN-END:variables
}
